name: Generate Contribution Snake

on:
  schedule:
    - cron: "0 0 * * *"

  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Generate snake animation
        uses: Platane/snk@v3
        with:
          github_user_name: Hadjerkhaw
          outputs: |
            dist/github-snake.svg?palette=github-dark
            dist/github-snake.gif?color_snake=#00d26a&color_dots=#161b22,#0e4429,#006d32,#26a641,#39d353

      - name: Publish generated files
        uses: crazy-max/ghaction-github-pages@v4
        with:
          build_dir: dist
          target_branch: output
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
